cc_binary (
    name = "main",
    srcs = ["main.cc"],
    deps = [
        ":support_handler",
    ],
)

cc_library (
    name = "support_handler",
    srcs = ["support_handler.cc"],
    hdrs = ["support_handler.h"],
)