cc_binary (
    name = "main",
    srcs = ["main.cc"],
    deps = [
        ":notification",
    ],
)

cc_library (
    name = "notification",
    srcs = ["notification.cc"],
    hdrs = ["notification.h"],
)