cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        ":car-prototype",
    ],
)

cc_library(
    name = "car-prototype",
    srcs = ["car-prototype.cc"],
    hdrs = ["car-prototype.h"],
    visibility = ["//visibility:public"],
)
