cc_binary (
    name = "main",
    srcs = ["main.cc"],
    deps = [
        ":shapes",
        ":colors",
    ],
)

cc_library (
    name = "colors",
    hdrs = ["colors.h"],
)

cc_library (
    name = "shapes",
    hdrs = ["shapes.h"],
)