cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        ":beverage-maker",
    ],
)

cc_library(
    name = "beverage-maker",
    srcs = ["beverage-maker.cc"],
    hdrs = ["beverage-maker.h"],
)